/***********************************************Learning CPP from CPP - Chapter 1*************************/


                                /****************************1.2**************************/

/*
*Theory*
-> Values:
    -> Numbers: Normal likhdo, eg: 5 or 3.02 etcc...
    -> Characters: '' mein | treated as only 1 symbol, eg: '1', 'C', '$'
    -> Text Values: " " mein | eg: "Hello"

-> RAM: Random Acess Memory
    - OS loads program into RAM
    - OS also reserves some extra space in RAM. For: store values entered by the user, to store data read in from a file or network, 
      or to store values calculated while the program is running (e.g. the sum of two values) so they can be used again later.
    - RAM = series of numbered boxes that can be used to store data while the program is running.


*/